name: Deploy to EC2 Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # update deployment to use the freshly pushed image
            IMAGE=docker.io/$andr266/spring-app:$:latest
            sudo k3s kubectl set image deployment/spring-app spring-app=$IMAGE --record || \
              sudo k3s kubectl apply -f ~/deploy/k8s/deployment.yaml
            sudo k3s kubectl rollout status deployment/spring-app --timeout=120s